// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_cc9afe4755847ade
#define INCLUDED_cc9afe4755847ade
#include "linc_lua.h"
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Type
#include <Type.h>
#endif
#ifndef INCLUDED_ValueType
#include <ValueType.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_haxe_ds_IntMap
#include <haxe/ds/IntMap.h>
#endif
#ifndef INCLUDED_haxe_ds_ObjectMap
#include <haxe/ds/ObjectMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_llua_Convert
#include <llua/Convert.h>
#endif
#ifndef INCLUDED_llua_LuaCallback
#include <llua/LuaCallback.h>
#endif
#ifndef INCLUDED_llua_LuaException
#include <llua/LuaException.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_4b5f1938ae03ba97_26_toLua,"llua.Convert","toLua",0x3fb91700,"llua.Convert.toLua","llua/Convert.hx",26,0x49e36a6e)
HX_LOCAL_STACK_FRAME(_hx_pos_4b5f1938ae03ba97_61_arrayToLua,"llua.Convert","arrayToLua",0x07e2abc1,"llua.Convert.arrayToLua","llua/Convert.hx",61,0x49e36a6e)
HX_LOCAL_STACK_FRAME(_hx_pos_4b5f1938ae03ba97_71_mapToLua,"llua.Convert","mapToLua",0x655c929e,"llua.Convert.mapToLua","llua/Convert.hx",71,0x49e36a6e)
HX_LOCAL_STACK_FRAME(_hx_pos_4b5f1938ae03ba97_83_anonToLua,"llua.Convert","anonToLua",0x16c64594,"llua.Convert.anonToLua","llua/Convert.hx",83,0x49e36a6e)
HX_LOCAL_STACK_FRAME(_hx_pos_4b5f1938ae03ba97_97_setGlobal,"llua.Convert","setGlobal",0xf2a87028,"llua.Convert.setGlobal","llua/Convert.hx",97,0x49e36a6e)
HX_LOCAL_STACK_FRAME(_hx_pos_4b5f1938ae03ba97_108_fromLua,"llua.Convert","fromLua",0x7fff7d31,"llua.Convert.fromLua","llua/Convert.hx",108,0x49e36a6e)
HX_LOCAL_STACK_FRAME(_hx_pos_4b5f1938ae03ba97_137_toHaxeObj,"llua.Convert","toHaxeObj",0x234db0b9,"llua.Convert.toHaxeObj","llua/Convert.hx",137,0x49e36a6e)
HX_LOCAL_STACK_FRAME(_hx_pos_4b5f1938ae03ba97_200_callLuaFunction,"llua.Convert","callLuaFunction",0x8607aeb5,"llua.Convert.callLuaFunction","llua/Convert.hx",200,0x49e36a6e)
HX_LOCAL_STACK_FRAME(_hx_pos_4b5f1938ae03ba97_231_callLuaFuncNoReturns,"llua.Convert","callLuaFuncNoReturns",0x885666e1,"llua.Convert.callLuaFuncNoReturns","llua/Convert.hx",231,0x49e36a6e)
HX_LOCAL_STACK_FRAME(_hx_pos_4b5f1938ae03ba97_245_callback_handler,"llua.Convert","callback_handler",0x2af82ced,"llua.Convert.callback_handler","llua/Convert.hx",245,0x49e36a6e)
HX_LOCAL_STACK_FRAME(_hx_pos_4b5f1938ae03ba97_16_boot,"llua.Convert","boot",0xcfa7298f,"llua.Convert.boot","llua/Convert.hx",16,0x49e36a6e)
namespace llua{

void Convert_obj::__construct() { }

Dynamic Convert_obj::__CreateEmpty() { return new Convert_obj; }

void *Convert_obj::_hx_vtable = 0;

Dynamic Convert_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Convert_obj > _hx_result = new Convert_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Convert_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x70578207;
}

bool Convert_obj::enableUnsupportedTraces;

bool Convert_obj::toLua( cpp::Reference<lua_State> l, ::Dynamic val){
            	HX_STACKFRAME(&_hx_pos_4b5f1938ae03ba97_26_toLua)
HXLINE(  27)		{
HXLINE(  27)			 ::ValueType _g = ::Type_obj::_hx_typeof(val);
HXDLIN(  27)			switch((int)(_g->_hx_getIndex())){
            				case (int)0: {
HXLINE(  29)					lua_pushnil(l);
            				}
            				break;
            				case (int)1: {
HXLINE(  33)					lua_pushinteger(l,::hx::TCast< int >::cast(val));
            				}
            				break;
            				case (int)2: {
HXLINE(  35)					lua_pushnumber(l,( (Float)(val) ));
            				}
            				break;
            				case (int)3: {
HXLINE(  31)					int _hx_tmp;
HXDLIN(  31)					if (( (bool)(val) )) {
HXLINE(  31)						_hx_tmp = 1;
            					}
            					else {
HXLINE(  31)						_hx_tmp = 0;
            					}
HXDLIN(  31)					lua_pushboolean(l,_hx_tmp);
            				}
            				break;
            				case (int)4: {
HXLINE(  43)					::Array< ::String > fields = ::Reflect_obj::fields(val);
HXDLIN(  43)					lua_createtable(l,0,fields->length);
HXDLIN(  43)					{
HXLINE(  43)						int _g1 = 0;
HXDLIN(  43)						while((_g1 < fields->length)){
HXLINE(  43)							::String n = fields->__get(_g1);
HXDLIN(  43)							_g1 = (_g1 + 1);
HXDLIN(  43)							lua_pushstring(l,n);
HXDLIN(  43)							::llua::Convert_obj::toLua(l,::Reflect_obj::field(val,n));
HXDLIN(  43)							lua_settable(l,-3);
            						}
            					}
            				}
            				break;
            				case (int)5: {
HXLINE(  49)					if (::llua::Convert_obj::enableUnsupportedTraces) {
HXLINE(  50)						::haxe::Log_obj::trace(HX_("TFunction push not supported via toLua; use Lua_helper.add_callback instead.",08,9b,35,d9),::hx::SourceInfo(HX_("llua/Convert.hx",6e,6a,e3,49),50,HX_("llua.Convert",31,b8,44,19),HX_("toLua",fd,0a,14,14)));
            					}
HXLINE(  51)					return false;
            				}
            				break;
            				case (int)6: {
HXLINE(  40)					::hx::Class _hx_switch_0 = _g->_hx_getObject(0).StaticCast< ::hx::Class >();
            					if (  (_hx_switch_0==::hx::ArrayBase::__mClass) ){
HXLINE(  39)						::cpp::VirtualArray arr = ( (::cpp::VirtualArray)(val) );
HXDLIN(  39)						lua_createtable(l,arr->get_length(),0);
HXDLIN(  39)						{
HXLINE(  39)							int _g_current = 0;
HXDLIN(  39)							::cpp::VirtualArray _g_array = arr;
HXDLIN(  39)							while((_g_current < _g_array->get_length())){
HXLINE(  39)								 ::Dynamic _g_value = _g_array->__get(_g_current);
HXDLIN(  39)								_g_current = (_g_current + 1);
HXDLIN(  39)								int _g_key = (_g_current - 1);
HXDLIN(  39)								int i = _g_key;
HXDLIN(  39)								 ::Dynamic v = _g_value;
HXDLIN(  39)								{
HXLINE(  39)									::llua::Convert_obj::toLua(l,v);
HXDLIN(  39)									lua_rawseti(l,-2,(i + 1));
            								}
            							}
            						}
HXDLIN(  39)						goto _hx_goto_1;
            					}
            					if (  (_hx_switch_0==::hx::ClassOf< ::String >()) ){
HXLINE(  37)						lua_pushstring(l,::hx::TCast< ::String >::cast(val));
HXDLIN(  37)						goto _hx_goto_1;
            					}
            					if (  (_hx_switch_0==::hx::ClassOf< ::haxe::ds::IntMap >()) ||  (_hx_switch_0==::hx::ClassOf< ::haxe::ds::ObjectMap >()) ||  (_hx_switch_0==::hx::ClassOf< ::haxe::ds::StringMap >()) ){
HXLINE(  41)						::llua::Convert_obj::mapToLua(l,val);
HXDLIN(  41)						goto _hx_goto_1;
            					}
            					/* default */{
HXLINE(  53)						if (::llua::Convert_obj::enableUnsupportedTraces) {
HXLINE(  54)							 ::Dynamic _hx_tmp1 = ::haxe::Log_obj::trace;
HXDLIN(  54)							::String _hx_tmp2;
HXDLIN(  54)							if (::hx::IsNull( val )) {
HXLINE(  54)								_hx_tmp2 = HX_("null",87,9e,0e,49);
            							}
            							else {
HXLINE(  54)								_hx_tmp2 = ::Std_obj::string(val);
            							}
HXDLIN(  54)							::String _hx_tmp3 = ((((HX_("Haxe value ",29,b0,3b,0f) + _hx_tmp2) + HX_(" of type ",7d,e8,d0,a2)) + ::Std_obj::string(::Type_obj::_hx_typeof(val))) + HX_(" not supported for toLua.",c7,d7,81,ff));
HXDLIN(  54)							_hx_tmp1(_hx_tmp3,::hx::SourceInfo(HX_("llua/Convert.hx",6e,6a,e3,49),54,HX_("llua.Convert",31,b8,44,19),HX_("toLua",fd,0a,14,14)));
            						}
HXLINE(  55)						return false;
            					}
            					_hx_goto_1:;
            				}
            				break;
            				default:{
HXLINE(  53)					if (::llua::Convert_obj::enableUnsupportedTraces) {
HXLINE(  54)						 ::Dynamic _hx_tmp4 = ::haxe::Log_obj::trace;
HXDLIN(  54)						::String _hx_tmp5;
HXDLIN(  54)						if (::hx::IsNull( val )) {
HXLINE(  54)							_hx_tmp5 = HX_("null",87,9e,0e,49);
            						}
            						else {
HXLINE(  54)							_hx_tmp5 = ::Std_obj::string(val);
            						}
HXDLIN(  54)						::String _hx_tmp6 = ((((HX_("Haxe value ",29,b0,3b,0f) + _hx_tmp5) + HX_(" of type ",7d,e8,d0,a2)) + ::Std_obj::string(::Type_obj::_hx_typeof(val))) + HX_(" not supported for toLua.",c7,d7,81,ff));
HXDLIN(  54)						_hx_tmp4(_hx_tmp6,::hx::SourceInfo(HX_("llua/Convert.hx",6e,6a,e3,49),54,HX_("llua.Convert",31,b8,44,19),HX_("toLua",fd,0a,14,14)));
            					}
HXLINE(  55)					return false;
            				}
            			}
            		}
HXLINE(  57)		return true;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Convert_obj,toLua,return )

void Convert_obj::arrayToLua( cpp::Reference<lua_State> l,::cpp::VirtualArray arr){
            	HX_STACKFRAME(&_hx_pos_4b5f1938ae03ba97_61_arrayToLua)
HXLINE(  62)		lua_createtable(l,arr->get_length(),0);
HXLINE(  63)		{
HXLINE(  63)			int _g_current = 0;
HXDLIN(  63)			::cpp::VirtualArray _g_array = arr;
HXDLIN(  63)			while((_g_current < _g_array->get_length())){
HXLINE(  63)				 ::Dynamic _g_value = _g_array->__get(_g_current);
HXDLIN(  63)				_g_current = (_g_current + 1);
HXDLIN(  63)				int _g_key = (_g_current - 1);
HXDLIN(  63)				int i = _g_key;
HXDLIN(  63)				 ::Dynamic v = _g_value;
HXDLIN(  63)				{
HXLINE(  65)					::llua::Convert_obj::toLua(l,v);
HXLINE(  66)					lua_rawseti(l,-2,(i + 1));
            				}
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Convert_obj,arrayToLua,(void))

void Convert_obj::mapToLua( cpp::Reference<lua_State> l, ::Dynamic res){
            	HX_STACKFRAME(&_hx_pos_4b5f1938ae03ba97_71_mapToLua)
HXLINE(  72)		lua_createtable(l,0,0);
HXLINE(  74)		::Dynamic map = res;
HXLINE(  75)		{
HXLINE(  75)			 ::Dynamic _g = ::haxe::IMap_obj::keyValueIterator(map);
HXDLIN(  75)			while(( (bool)(_g->__Field(HX_("hasNext",6d,a5,46,18),::hx::paccDynamic)()) )){
HXLINE(  75)				 ::Dynamic _g1 = _g->__Field(HX_("next",f3,84,02,49),::hx::paccDynamic)();
HXDLIN(  75)				 ::Dynamic key =  ::Dynamic(_g1->__Field(HX_("key",9f,89,51,00),::hx::paccDynamic));
HXDLIN(  75)				 ::Dynamic val =  ::Dynamic(_g1->__Field(HX_("value",71,7f,b8,31),::hx::paccDynamic));
HXDLIN(  75)				{
HXLINE(  76)					::llua::Convert_obj::toLua(l,key);
HXLINE(  77)					::llua::Convert_obj::toLua(l,val);
HXLINE(  78)					lua_settable(l,-3);
            				}
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Convert_obj,mapToLua,(void))

void Convert_obj::anonToLua( cpp::Reference<lua_State> l, ::Dynamic res){
            	HX_STACKFRAME(&_hx_pos_4b5f1938ae03ba97_83_anonToLua)
HXLINE(  84)		::Array< ::String > fields = ::Reflect_obj::fields(res);
HXLINE(  85)		lua_createtable(l,0,fields->length);
HXLINE(  86)		{
HXLINE(  86)			int _g = 0;
HXDLIN(  86)			while((_g < fields->length)){
HXLINE(  86)				::String n = fields->__get(_g);
HXDLIN(  86)				_g = (_g + 1);
HXLINE(  87)				lua_pushstring(l,n);
HXLINE(  88)				::llua::Convert_obj::toLua(l,::Reflect_obj::field(res,n));
HXLINE(  89)				lua_settable(l,-3);
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Convert_obj,anonToLua,(void))

void Convert_obj::setGlobal( cpp::Reference<lua_State> l,::String index, ::Dynamic value){
            	HX_STACKFRAME(&_hx_pos_4b5f1938ae03ba97_97_setGlobal)
HXLINE(  98)		::llua::Convert_obj::toLua(l,value);
HXLINE(  99)		lua_setglobal(l,index);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(Convert_obj,setGlobal,(void))

 ::Dynamic Convert_obj::fromLua( cpp::Reference<lua_State> l,int v){
            	HX_GC_STACKFRAME(&_hx_pos_4b5f1938ae03ba97_108_fromLua)
HXDLIN( 108)		switch((int)(lua_type(l,v))){
            			case (int)0: {
HXLINE( 110)				return null();
            			}
            			break;
            			case (int)1: {
HXLINE( 112)				return (lua_toboolean(l,v) != 0);
            			}
            			break;
            			case (int)3: {
HXLINE( 115)				Float n = lua_tonumber(l,v);
HXLINE( 116)				int ni = lua_tointeger(l,v);
HXLINE( 117)				if ((n == ni)) {
HXLINE( 117)					return ni;
            				}
            				else {
HXLINE( 117)					return n;
            				}
            			}
            			break;
            			case (int)4: {
HXLINE( 119)				return linc::lua::tostring(l,v);
            			}
            			break;
            			case (int)5: {
HXLINE( 121)				return ::llua::Convert_obj::toHaxeObj(l,v);
            			}
            			break;
            			case (int)6: {
HXLINE( 124)				lua_pushvalue(l,v);
HXLINE( 125)				return  ::llua::LuaCallback_obj::__alloc( HX_CTX ,l,luaL_ref(l,-10000));
            			}
            			break;
            			default:{
HXLINE( 127)				if (::llua::Convert_obj::enableUnsupportedTraces) {
HXLINE( 128)					 ::Dynamic _hx_tmp = ::haxe::Log_obj::trace;
HXDLIN( 128)					::String _hx_tmp1 = ((((HX_("Lua value at ",16,5b,54,16) + v) + HX_(" of type ",7d,e8,d0,a2)) + lua_type(l,v)) + HX_(" not supported for fromLua.",b6,74,18,f7));
HXDLIN( 128)					_hx_tmp(_hx_tmp1,::hx::SourceInfo(HX_("llua/Convert.hx",6e,6a,e3,49),128,HX_("llua.Convert",31,b8,44,19),HX_("fromLua",6e,2a,fd,57)));
            				}
HXLINE( 129)				return null();
            			}
            		}
HXLINE( 108)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Convert_obj,fromLua,return )

 ::Dynamic Convert_obj::toHaxeObj( cpp::Reference<lua_State> l,int i){
            	HX_STACKFRAME(&_hx_pos_4b5f1938ae03ba97_137_toHaxeObj)
HXLINE( 138)		bool isArray = true;
HXLINE( 139)		int maxIndex = 0;
HXLINE( 140)		int count = 0;
HXLINE(  21)		{
HXLINE(  23)			int _hx___tbl_idx;
HXDLIN(  23)			if ((i < 0)) {
HXLINE(  23)				_hx___tbl_idx = (i - 1);
            			}
            			else {
HXLINE(  23)				_hx___tbl_idx = i;
            			}
HXLINE(  24)			lua_pushnil(l);
HXLINE(  25)			while((lua_next(l,_hx___tbl_idx) != 0)){
HXLINE( 143)				{
HXLINE( 144)					count = (count + 1);
HXLINE( 145)					if (isArray) {
HXLINE( 146)						if ((lua_type(l,-2) != 3)) {
HXLINE( 147)							isArray = false;
            						}
            						else {
HXLINE( 149)							Float n = lua_tonumber(l,-2);
HXLINE( 150)							int ni = ::Std_obj::_hx_int(n);
HXLINE( 151)							bool _hx_tmp;
HXDLIN( 151)							if ((n == ni)) {
HXLINE( 151)								_hx_tmp = (ni < 1);
            							}
            							else {
HXLINE( 151)								_hx_tmp = true;
            							}
HXDLIN( 151)							if (_hx_tmp) {
HXLINE( 152)								isArray = false;
            							}
            							else {
HXLINE( 153)								if ((ni > maxIndex)) {
HXLINE( 154)									maxIndex = ni;
            								}
            							}
            						}
            					}
            				}
HXLINE(  28)				lua_pop(l,1);
            			}
            		}
HXLINE( 160)		if ((count == 0)) {
HXLINE( 160)			return  ::Dynamic(::hx::Anon_obj::Create(0));
            		}
HXLINE( 163)		bool _hx_tmp1;
HXDLIN( 163)		if (isArray) {
HXLINE( 163)			_hx_tmp1 = (maxIndex == count);
            		}
            		else {
HXLINE( 163)			_hx_tmp1 = false;
            		}
HXDLIN( 163)		if (_hx_tmp1) {
HXLINE( 164)			::cpp::VirtualArray arr = ::cpp::VirtualArray_obj::__new(0);
HXLINE( 165)			arr->resize(count);
HXLINE(  21)			{
HXLINE(  23)				int _hx___tbl_idx1;
HXDLIN(  23)				if ((i < 0)) {
HXLINE(  23)					_hx___tbl_idx1 = (i - 1);
            				}
            				else {
HXLINE(  23)					_hx___tbl_idx1 = i;
            				}
HXLINE(  24)				lua_pushnil(l);
HXLINE(  25)				while((lua_next(l,_hx___tbl_idx1) != 0)){
HXLINE( 167)					arr->set((::Std_obj::_hx_int(lua_tonumber(l,-2)) - 1),::llua::Convert_obj::fromLua(l,-1));
HXLINE(  28)					lua_pop(l,1);
            				}
            			}
HXLINE( 169)			return arr;
            		}
HXLINE( 173)		 ::Dynamic obj =  ::Dynamic(::hx::Anon_obj::Create(0));
HXLINE(  21)		{
HXLINE(  23)			int _hx___tbl_idx2;
HXDLIN(  23)			if ((i < 0)) {
HXLINE(  23)				_hx___tbl_idx2 = (i - 1);
            			}
            			else {
HXLINE(  23)				_hx___tbl_idx2 = i;
            			}
HXLINE(  24)			lua_pushnil(l);
HXLINE(  25)			while((lua_next(l,_hx___tbl_idx2) != 0)){
HXLINE( 174)				{
HXLINE( 175)					::String key;
HXDLIN( 175)					int _g = lua_type(l,-2);
HXLINE( 176)					int t = _g;
HXLINE( 175)					if ((t == 4)) {
HXLINE( 175)						key = linc::lua::tostring(l,-2);
            					}
            					else {
HXLINE( 177)						int t1 = _g;
HXDLIN( 177)						if ((t1 == 3)) {
HXLINE( 175)							key = ::Std_obj::string(lua_tonumber(l,-2));
            						}
            						else {
HXLINE( 175)							key = null();
            						}
            					}
HXLINE( 180)					if (::hx::IsNotNull( key )) {
HXLINE( 180)						 ::Dynamic value = ::llua::Convert_obj::fromLua(l,-1);
HXDLIN( 180)						::Reflect_obj::setField(obj,key,value);
            					}
            				}
HXLINE(  28)				lua_pop(l,1);
            			}
            		}
HXLINE( 182)		return obj;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Convert_obj,toHaxeObj,return )

 ::Dynamic Convert_obj::callLuaFunction( cpp::Reference<lua_State> l,::String func,::cpp::VirtualArray args, ::Dynamic __o_multipleReturns){
            		 ::Dynamic multipleReturns = __o_multipleReturns;
            		if (::hx::IsNull(__o_multipleReturns)) multipleReturns = false;
            	HX_GC_STACKFRAME(&_hx_pos_4b5f1938ae03ba97_200_callLuaFunction)
HXLINE( 201)		if (::hx::IsNotNull( func )) {
HXLINE( 201)			lua_getglobal(l,func);
            		}
HXLINE( 203)		int argc = 0;
HXLINE( 204)		if (::hx::IsNotNull( args )) {
HXLINE( 205)			argc = args->get_length();
HXLINE( 206)			{
HXLINE( 206)				int _g = 0;
HXDLIN( 206)				while((_g < args->get_length())){
HXLINE( 206)					 ::Dynamic arg = args->__get(_g);
HXDLIN( 206)					_g = (_g + 1);
HXDLIN( 206)					::llua::Convert_obj::toLua(l,arg);
            				}
            			}
            		}
HXLINE( 209)		if (( (bool)(multipleReturns) )) {
HXLINE( 210)			{
HXLINE( 210)				int status = lua_pcall(l,argc,-1,0);
HXDLIN( 210)				if ((status != 0)) {
HXLINE( 210)					HX_STACK_DO_THROW( ::llua::LuaException_obj::__alloc( HX_CTX ,null(),null(),status,l));
            				}
            			}
HXLINE( 211)			int nresults = lua_gettop(l);
HXLINE( 212)			::cpp::VirtualArray ret = ::cpp::VirtualArray_obj::__new(0);
HXLINE( 213)			{
HXLINE( 213)				int _g1 = 0;
HXDLIN( 213)				int _g2 = nresults;
HXDLIN( 213)				while((_g1 < _g2)){
HXLINE( 213)					_g1 = (_g1 + 1);
HXDLIN( 213)					int i = (_g1 - 1);
HXLINE( 214)					ret->push(::llua::Convert_obj::fromLua(l,(i + 1)));
            				}
            			}
HXLINE( 215)			lua_settop(l,0);
HXLINE( 216)			return ret;
            		}
            		else {
HXLINE( 218)			{
HXLINE( 218)				int status1 = lua_pcall(l,argc,1,0);
HXDLIN( 218)				if ((status1 != 0)) {
HXLINE( 218)					HX_STACK_DO_THROW( ::llua::LuaException_obj::__alloc( HX_CTX ,null(),null(),status1,l));
            				}
            			}
HXLINE( 220)			 ::Dynamic result = ::llua::Convert_obj::fromLua(l,-1);
HXLINE( 221)			lua_pop(l,1);
HXLINE( 222)			return result;
            		}
HXLINE( 209)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC4(Convert_obj,callLuaFunction,return )

void Convert_obj::callLuaFuncNoReturns( cpp::Reference<lua_State> l,::String func,::cpp::VirtualArray args){
            	HX_GC_STACKFRAME(&_hx_pos_4b5f1938ae03ba97_231_callLuaFuncNoReturns)
HXLINE( 232)		lua_getglobal(l,func);
HXLINE( 233)		int argc = 0;
HXLINE( 234)		if (::hx::IsNotNull( args )) {
HXLINE( 235)			argc = args->get_length();
HXLINE( 236)			{
HXLINE( 236)				int _g = 0;
HXDLIN( 236)				while((_g < args->get_length())){
HXLINE( 236)					 ::Dynamic arg = args->__get(_g);
HXDLIN( 236)					_g = (_g + 1);
HXDLIN( 236)					::llua::Convert_obj::toLua(l,arg);
            				}
            			}
            		}
HXLINE( 238)		{
HXLINE( 238)			int status = lua_pcall(l,argc,0,0);
HXDLIN( 238)			if ((status != 0)) {
HXLINE( 238)				HX_STACK_DO_THROW( ::llua::LuaException_obj::__alloc( HX_CTX ,null(),null(),status,l));
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(Convert_obj,callLuaFuncNoReturns,(void))

int Convert_obj::callback_handler( ::Dynamic cbf, cpp::Reference<lua_State> l, ::Dynamic object){
            	HX_STACKFRAME(&_hx_pos_4b5f1938ae03ba97_245_callback_handler)
HXLINE( 246)		int nparams = lua_gettop(l);
HXLINE( 247)		::cpp::VirtualArray _g = ::cpp::VirtualArray_obj::__new(0);
HXDLIN( 247)		{
HXLINE( 247)			int _g1 = 0;
HXDLIN( 247)			int _g2 = nparams;
HXDLIN( 247)			while((_g1 < _g2)){
HXLINE( 247)				_g1 = (_g1 + 1);
HXDLIN( 247)				int i = (_g1 - 1);
HXDLIN( 247)				_g->push(::llua::Convert_obj::fromLua(l,(i + 1)));
            			}
            		}
HXDLIN( 247)		::cpp::VirtualArray args = _g;
HXLINE( 248)		try {
            			HX_STACK_CATCHABLE( ::Dynamic, 0);
HXLINE( 249)			 ::Dynamic ret = ::Reflect_obj::callMethod(object,cbf,args);
HXLINE( 250)			if (::hx::IsNotNull( ret )) {
HXLINE( 251)				::llua::Convert_obj::toLua(l,ret);
HXLINE( 252)				return 1;
            			}
            		} catch( ::Dynamic _hx_e) {
            			if (_hx_e.IsClass<  ::Dynamic >() ){
            				HX_STACK_BEGIN_CATCH
            				 ::Dynamic _g3 = _hx_e;
HXLINE( 254)				{
HXLINE( 254)					null();
            				}
HXDLIN( 254)				 ::Dynamic e = _g3;
HXLINE( 255)				::String msg;
HXDLIN( 255)				if (::hx::IsNotNull( e->__Field(HX_("message",c7,35,11,9a),::hx::paccDynamic) )) {
HXLINE( 255)					msg = ( (::String)(e->__Field(HX_("message",c7,35,11,9a),::hx::paccDynamic)) );
            				}
            				else {
HXLINE( 255)					msg = ::Std_obj::string(e);
            				}
HXLINE( 256)				::haxe::Log_obj::trace((HX_("llua callback error: ",e7,e0,fc,6c) + msg),::hx::SourceInfo(HX_("llua/Convert.hx",6e,6a,e3,49),256,HX_("llua.Convert",31,b8,44,19),HX_("callback_handler",10,70,1b,10)));
HXLINE( 257)				HX_STACK_DO_THROW(e);
            			}
            			else {
            				HX_STACK_DO_THROW(_hx_e);
            			}
            		}
HXLINE( 259)		return 0;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(Convert_obj,callback_handler,return )


Convert_obj::Convert_obj()
{
}

bool Convert_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"toLua") ) { outValue = toLua_dyn(); return true; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"fromLua") ) { outValue = fromLua_dyn(); return true; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"mapToLua") ) { outValue = mapToLua_dyn(); return true; }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"anonToLua") ) { outValue = anonToLua_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"setGlobal") ) { outValue = setGlobal_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"toHaxeObj") ) { outValue = toHaxeObj_dyn(); return true; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"arrayToLua") ) { outValue = arrayToLua_dyn(); return true; }
		break;
	case 15:
		if (HX_FIELD_EQ(inName,"callLuaFunction") ) { outValue = callLuaFunction_dyn(); return true; }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"callback_handler") ) { outValue = callback_handler_dyn(); return true; }
		break;
	case 20:
		if (HX_FIELD_EQ(inName,"callLuaFuncNoReturns") ) { outValue = callLuaFuncNoReturns_dyn(); return true; }
		break;
	case 23:
		if (HX_FIELD_EQ(inName,"enableUnsupportedTraces") ) { outValue = ( enableUnsupportedTraces ); return true; }
	}
	return false;
}

bool Convert_obj::__SetStatic(const ::String &inName,Dynamic &ioValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 23:
		if (HX_FIELD_EQ(inName,"enableUnsupportedTraces") ) { enableUnsupportedTraces=ioValue.Cast< bool >(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *Convert_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo Convert_obj_sStaticStorageInfo[] = {
	{::hx::fsBool,(void *) &Convert_obj::enableUnsupportedTraces,HX_("enableUnsupportedTraces",e0,6a,4d,f5)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static void Convert_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(Convert_obj::enableUnsupportedTraces,"enableUnsupportedTraces");
};

#ifdef HXCPP_VISIT_ALLOCS
static void Convert_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(Convert_obj::enableUnsupportedTraces,"enableUnsupportedTraces");
};

#endif

::hx::Class Convert_obj::__mClass;

static ::String Convert_obj_sStaticFields[] = {
	HX_("enableUnsupportedTraces",e0,6a,4d,f5),
	HX_("toLua",fd,0a,14,14),
	HX_("arrayToLua",a4,22,41,0e),
	HX_("mapToLua",c1,7a,56,8b),
	HX_("anonToLua",11,7c,77,2b),
	HX_("setGlobal",a5,a6,59,07),
	HX_("fromLua",6e,2a,fd,57),
	HX_("toHaxeObj",36,e7,fe,37),
	HX_("callLuaFunction",f2,60,80,8a),
	HX_("callLuaFuncNoReturns",84,77,dd,3a),
	HX_("callback_handler",10,70,1b,10),
	::String(null())
};

void Convert_obj::__register()
{
	Convert_obj _hx_dummy;
	Convert_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("llua.Convert",31,b8,44,19);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Convert_obj::__GetStatic;
	__mClass->mSetStaticField = &Convert_obj::__SetStatic;
	__mClass->mMarkFunc = Convert_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Convert_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< Convert_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = Convert_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Convert_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Convert_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Convert_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_4b5f1938ae03ba97_16_boot)
HXDLIN(  16)		enableUnsupportedTraces = false;
            	}
}

} // end namespace llua
