// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_cc9afe4755847ade
#define INCLUDED_cc9afe4755847ade
#include "linc_lua.h"
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_llua_Convert
#include <llua/Convert.h>
#endif
#ifndef INCLUDED_llua_LuaCallback
#include <llua/LuaCallback.h>
#endif
#ifndef INCLUDED_llua_LuaException
#include <llua/LuaException.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_d6492622815d6e1e_10_new,"llua.LuaCallback","new",0xe40f834d,"llua.LuaCallback.new","llua/LuaCallback.hx",10,0xd770c484)
HX_LOCAL_STACK_FRAME(_hx_pos_d6492622815d6e1e_32_call,"llua.LuaCallback","call",0xa23af511,"llua.LuaCallback.call","llua/LuaCallback.hx",32,0xd770c484)
HX_LOCAL_STACK_FRAME(_hx_pos_d6492622815d6e1e_65_callWithReturn,"llua.LuaCallback","callWithReturn",0xc5cd2fc7,"llua.LuaCallback.callWithReturn","llua/LuaCallback.hx",65,0xd770c484)
HX_LOCAL_STACK_FRAME(_hx_pos_d6492622815d6e1e_86_dispose,"llua.LuaCallback","dispose",0x61c0ae0c,"llua.LuaCallback.dispose","llua/LuaCallback.hx",86,0xd770c484)
namespace llua{

void LuaCallback_obj::__construct( cpp::Reference<lua_State> lua,int ref){
            	HX_STACKFRAME(&_hx_pos_d6492622815d6e1e_10_new)
HXLINE(  19)		this->disposed = false;
HXLINE(  22)		this->l = lua;
HXLINE(  23)		this->ref = ref;
            	}

Dynamic LuaCallback_obj::__CreateEmpty() { return new LuaCallback_obj; }

void *LuaCallback_obj::_hx_vtable = 0;

Dynamic LuaCallback_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< LuaCallback_obj > _hx_result = new LuaCallback_obj();
	_hx_result->__construct(inArgs[0],inArgs[1]);
	return _hx_result;
}

bool LuaCallback_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x7f98fc19;
}

void LuaCallback_obj::call(::cpp::VirtualArray args){
            	HX_STACKFRAME(&_hx_pos_d6492622815d6e1e_32_call)
HXLINE(  33)		if (this->disposed) {
HXLINE(  34)			::haxe::Log_obj::trace(HX_W(u"LuaCallback.call() called after dispose() \u2014 ignoring.",03de,07f2),::hx::SourceInfo(HX_("llua/LuaCallback.hx",84,c4,70,d7),34,HX_("llua.LuaCallback",db,d8,46,84),HX_("call",9e,18,ba,41)));
HXLINE(  35)			return;
            		}
HXLINE(  37)		lua_rawgeti(this->l,-10000,this->ref);
HXLINE(  38)		if ((lua_isfunction(this->l,-1) == 0)) {
HXLINE(  39)			lua_pop(this->l,1);
HXLINE(  40)			::haxe::Log_obj::trace(HX_("LuaCallback: registry ref is no longer a function.",16,fa,6b,02),::hx::SourceInfo(HX_("llua/LuaCallback.hx",84,c4,70,d7),40,HX_("llua.LuaCallback",db,d8,46,84),HX_("call",9e,18,ba,41)));
HXLINE(  41)			return;
            		}
HXLINE(  43)		if (::hx::IsNull( args )) {
HXLINE(  43)			args = ::cpp::VirtualArray_obj::__new(0);
            		}
HXLINE(  44)		{
HXLINE(  44)			int _g = 0;
HXDLIN(  44)			while((_g < args->get_length())){
HXLINE(  44)				 ::Dynamic arg = args->__get(_g);
HXDLIN(  44)				_g = (_g + 1);
HXDLIN(  44)				::llua::Convert_obj::toLua(this->l,arg);
            			}
            		}
HXLINE(  45)		int status = lua_pcall(this->l,args->get_length(),0,0);
HXLINE(  46)		if ((status != 0)) {
HXLINE(  47)			::String err = linc::lua::tostring(this->l,-1);
HXLINE(  48)			lua_pop(this->l,1);
HXLINE(  49)			bool _hx_tmp;
HXDLIN(  49)			if (::hx::IsNotNull( err )) {
HXLINE(  49)				_hx_tmp = (err == HX_("",00,00,00,00));
            			}
            			else {
HXLINE(  49)				_hx_tmp = true;
            			}
HXDLIN(  49)			if (_hx_tmp) {
HXLINE(  50)				switch((int)(status)){
            					case (int)2: {
HXLINE(  51)						err = HX_("Runtime Error",40,fe,ae,fe);
            					}
            					break;
            					case (int)4: {
HXLINE(  52)						err = HX_("Memory Allocation Error",a7,0d,34,8f);
            					}
            					break;
            					case (int)5: {
HXLINE(  53)						err = HX_("Critical Error in error handler",b0,a4,2d,53);
            					}
            					break;
            					default:{
HXLINE(  54)						err = ((HX_("Unknown Error (status=",11,7d,ea,e1) + status) + HX_(")",29,00,00,00));
            					}
            				}
            			}
HXLINE(  57)			::haxe::Log_obj::trace((HX_("LuaCallback error: ",cb,c8,d1,40) + err),::hx::SourceInfo(HX_("llua/LuaCallback.hx",84,c4,70,d7),57,HX_("llua.LuaCallback",db,d8,46,84),HX_("call",9e,18,ba,41)));
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC1(LuaCallback_obj,call,(void))

::cpp::VirtualArray LuaCallback_obj::callWithReturn(::cpp::VirtualArray args){
            	HX_GC_STACKFRAME(&_hx_pos_d6492622815d6e1e_65_callWithReturn)
HXLINE(  66)		if (this->disposed) {
HXLINE(  66)			HX_STACK_DO_THROW(HX_("LuaCallback.callWithReturn() called after dispose()",f3,5f,40,81));
            		}
HXLINE(  67)		lua_rawgeti(this->l,-10000,this->ref);
HXLINE(  68)		if ((lua_isfunction(this->l,-1) == 0)) {
HXLINE(  69)			lua_pop(this->l,1);
HXLINE(  70)			HX_STACK_DO_THROW(HX_("LuaCallback: registry ref is no longer a function.",16,fa,6b,02));
            		}
HXLINE(  72)		if (::hx::IsNull( args )) {
HXLINE(  72)			args = ::cpp::VirtualArray_obj::__new(0);
            		}
HXLINE(  73)		{
HXLINE(  73)			int _g = 0;
HXDLIN(  73)			while((_g < args->get_length())){
HXLINE(  73)				 ::Dynamic arg = args->__get(_g);
HXDLIN(  73)				_g = (_g + 1);
HXDLIN(  73)				::llua::Convert_obj::toLua(this->l,arg);
            			}
            		}
HXLINE(  74)		{
HXLINE(  74)			 cpp::Reference<lua_State> l = this->l;
HXDLIN(  74)			int status = lua_pcall(this->l,args->get_length(),-1,0);
HXDLIN(  74)			if ((status != 0)) {
HXLINE(  74)				HX_STACK_DO_THROW( ::llua::LuaException_obj::__alloc( HX_CTX ,null(),null(),status,l));
            			}
            		}
HXLINE(  75)		int nresults = lua_gettop(this->l);
HXLINE(  76)		::cpp::VirtualArray _g1 = ::cpp::VirtualArray_obj::__new(0);
HXDLIN(  76)		{
HXLINE(  76)			int _g2 = 0;
HXDLIN(  76)			int _g3 = nresults;
HXDLIN(  76)			while((_g2 < _g3)){
HXLINE(  76)				_g2 = (_g2 + 1);
HXDLIN(  76)				int i = (_g2 - 1);
HXDLIN(  76)				_g1->push(::llua::Convert_obj::fromLua(this->l,(i + 1)));
            			}
            		}
HXDLIN(  76)		::cpp::VirtualArray ret = _g1;
HXLINE(  77)		lua_settop(this->l,0);
HXLINE(  78)		return ret;
            	}


HX_DEFINE_DYNAMIC_FUNC1(LuaCallback_obj,callWithReturn,return )

void LuaCallback_obj::dispose(){
            	HX_STACKFRAME(&_hx_pos_d6492622815d6e1e_86_dispose)
HXLINE(  87)		if (this->disposed) {
HXLINE(  87)			return;
            		}
HXLINE(  88)		this->disposed = true;
HXLINE(  89)		luaL_unref(this->l,-10000,this->ref);
            	}


HX_DEFINE_DYNAMIC_FUNC0(LuaCallback_obj,dispose,(void))


::hx::ObjectPtr< LuaCallback_obj > LuaCallback_obj::__new( cpp::Reference<lua_State> lua,int ref) {
	::hx::ObjectPtr< LuaCallback_obj > __this = new LuaCallback_obj();
	__this->__construct(lua,ref);
	return __this;
}

::hx::ObjectPtr< LuaCallback_obj > LuaCallback_obj::__alloc(::hx::Ctx *_hx_ctx, cpp::Reference<lua_State> lua,int ref) {
	LuaCallback_obj *__this = (LuaCallback_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(LuaCallback_obj), true, "llua.LuaCallback"));
	*(void **)__this = LuaCallback_obj::_hx_vtable;
	__this->__construct(lua,ref);
	return __this;
}

LuaCallback_obj::LuaCallback_obj()
{
}

void LuaCallback_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(LuaCallback);
	HX_MARK_MEMBER_NAME(l,"l");
	HX_MARK_MEMBER_NAME(ref,"ref");
	HX_MARK_MEMBER_NAME(disposed,"disposed");
	HX_MARK_END_CLASS();
}

void LuaCallback_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(l,"l");
	HX_VISIT_MEMBER_NAME(ref,"ref");
	HX_VISIT_MEMBER_NAME(disposed,"disposed");
}

::hx::Val LuaCallback_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"l") ) { return ::hx::Val( l ); }
		break;
	case 3:
		if (HX_FIELD_EQ(inName,"ref") ) { return ::hx::Val( ref ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"call") ) { return ::hx::Val( call_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"dispose") ) { return ::hx::Val( dispose_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"disposed") ) { return ::hx::Val( disposed ); }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"callWithReturn") ) { return ::hx::Val( callWithReturn_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val LuaCallback_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"l") ) { l=inValue.Cast<  cpp::Reference<lua_State> >(); return inValue; }
		break;
	case 3:
		if (HX_FIELD_EQ(inName,"ref") ) { ref=inValue.Cast< int >(); return inValue; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"disposed") ) { disposed=inValue.Cast< bool >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void LuaCallback_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("l",6c,00,00,00));
	outFields->push(HX_("ref",53,d9,56,00));
	outFields->push(HX_("disposed",e5,0a,a4,27));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo LuaCallback_obj_sMemberStorageInfo[] = {
	{::hx::fsUnknown /*  cpp::Reference<lua_State> */ ,(int)offsetof(LuaCallback_obj,l),HX_("l",6c,00,00,00)},
	{::hx::fsInt,(int)offsetof(LuaCallback_obj,ref),HX_("ref",53,d9,56,00)},
	{::hx::fsBool,(int)offsetof(LuaCallback_obj,disposed),HX_("disposed",e5,0a,a4,27)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *LuaCallback_obj_sStaticStorageInfo = 0;
#endif

static ::String LuaCallback_obj_sMemberFields[] = {
	HX_("l",6c,00,00,00),
	HX_("ref",53,d9,56,00),
	HX_("disposed",e5,0a,a4,27),
	HX_("call",9e,18,ba,41),
	HX_("callWithReturn",94,25,37,bd),
	HX_("dispose",9f,80,4c,bb),
	::String(null()) };

::hx::Class LuaCallback_obj::__mClass;

void LuaCallback_obj::__register()
{
	LuaCallback_obj _hx_dummy;
	LuaCallback_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("llua.LuaCallback",db,d8,46,84);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(LuaCallback_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< LuaCallback_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = LuaCallback_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = LuaCallback_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace llua
