// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_ValueType
#include <ValueType.h>
#endif
#ifndef INCLUDED_llua_Lua_helper
#include <llua/Lua_helper.h>
#endif
#ifndef INCLUDED_llua_Convert
#include <llua/Convert.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_llua_Macro
#include <llua/Macro.h>
#endif
#ifndef INCLUDED_llua_LuaException
#include <llua/LuaException.h>
#endif
#ifndef INCLUDED_llua_LuaCallback
#include <llua/LuaCallback.h>
#endif
#ifndef INCLUDED_haxe_iterators_MapKeyValueIterator
#include <haxe/iterators/MapKeyValueIterator.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayIterator
#include <haxe/iterators/ArrayIterator.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_haxe_ds_ObjectMap
#include <haxe/ds/ObjectMap.h>
#endif
#ifndef INCLUDED_haxe_ds_IntMap
#include <haxe/ds/IntMap.h>
#endif
#ifndef INCLUDED_haxe_NativeStackTrace
#include <haxe/NativeStackTrace.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_Type
#include <Type.h>
#endif
#ifndef INCLUDED_Test
#include <Test.h>
#endif
#ifndef INCLUDED_Testing
#include <Testing.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
::hx::RegisterResources( ::hx::GetResources() );
::ValueType_obj::__register();
::llua::Lua_helper_obj::__register();
::llua::Convert_obj::__register();
::haxe::Log_obj::__register();
::llua::Macro_obj::__register();
::llua::LuaException_obj::__register();
::llua::LuaCallback_obj::__register();
::haxe::iterators::MapKeyValueIterator_obj::__register();
::haxe::iterators::ArrayIterator_obj::__register();
::haxe::ds::StringMap_obj::__register();
::haxe::ds::ObjectMap_obj::__register();
::haxe::ds::IntMap_obj::__register();
::haxe::NativeStackTrace_obj::__register();
::haxe::Exception_obj::__register();
::haxe::IMap_obj::__register();
::Type_obj::__register();
::Test_obj::__register();
::Testing_obj::__register();
::Std_obj::__register();
::Reflect_obj::__register();
::ValueType_obj::__boot();
::haxe::Log_obj::__boot();
::llua::Convert_obj::__boot();
::llua::Lua_helper_obj::__boot();
}

