// Generated by Haxe 4.3.7
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"?",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Reflect.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Std.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Type.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/Exception.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/Log.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/NativeStackTrace.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/ds/IntMap.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/ds/ObjectMap.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/ds/StringMap.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/iterators/ArrayIterator.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/iterators/MapKeyValueIterator.hx",
"Test.hx",
"llua/Convert.hx",
"llua/Lua.hx",
"llua/LuaCallback.hx",
"llua/LuaException.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"C:\\Users\\Jeremiah Jr\\Downloads\\linc_luajit_funkinview\\test\\?",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Reflect.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Std.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Type.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\Exception.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\Log.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\NativeStackTrace.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\ds\\IntMap.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\ds\\ObjectMap.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\ds\\StringMap.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\iterators\\ArrayIterator.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\iterators\\MapKeyValueIterator.hx",
"C:\\Users\\Jeremiah Jr\\Downloads\\linc_luajit_funkinview\\test\\Test.hx",
"C:\\Users\\Jeremiah Jr\\Downloads\\linc_luajit_funkinview\\llua\\Convert.hx",
"C:\\Users\\Jeremiah Jr\\Downloads\\linc_luajit_funkinview\\llua\\Lua.hx",
"C:\\Users\\Jeremiah Jr\\Downloads\\linc_luajit_funkinview\\llua\\LuaCallback.hx",
"C:\\Users\\Jeremiah Jr\\Downloads\\linc_luajit_funkinview\\llua\\LuaException.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Reflect",
"Std",
"Testing",
"Test",
"Type",
"haxe.Exception",
"haxe.Log",
"haxe.NativeStackTrace",
"haxe.ds.IntMap",
"haxe.ds.ObjectMap",
"haxe.ds.StringMap",
"haxe.iterators.ArrayIterator",
"haxe.iterators.MapKeyValueIterator",
"llua.Convert",
"llua.Lua_helper",
"llua.LuaCallback",
"llua.LuaException",
"llua.Macro",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
