// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_cc9afe4755847ade
#define INCLUDED_cc9afe4755847ade
#include "linc_lua.h"
#endif
#ifndef INCLUDED_Test
#include <Test.h>
#endif
#ifndef INCLUDED_Testing
#include <Testing.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_llua_Convert
#include <llua/Convert.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_df13cafffbed243f_20_main,"Test","main",0x9c6c95b5,"Test.main","Test.hx",20,0x8afb218c)

void Test_obj::__construct() { }

Dynamic Test_obj::__CreateEmpty() { return new Test_obj; }

void *Test_obj::_hx_vtable = 0;

Dynamic Test_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Test_obj > _hx_result = new Test_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Test_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x0c25ea96;
}

void Test_obj::main(){
            	HX_GC_STACKFRAME(&_hx_pos_df13cafffbed243f_20_main)
HXLINE(  22)		 cpp::Reference<lua_State> vm = luaL_newstate();
HXLINE(  23)		luaL_openlibs(vm);
HXLINE(  24)		 ::Dynamic _hx_tmp = ::haxe::Log_obj::trace;
HXDLIN(  24)		::String _hx_tmp1 = (HX_("Lua version: ",36,0b,c4,a9) + linc::lua::version());
HXDLIN(  24)		_hx_tmp(_hx_tmp1,::hx::SourceInfo(HX_("test/Test.hx",8f,7f,93,a4),24,HX_("Test",72,f4,d2,37),HX_("main",39,38,56,48)));
HXLINE(  25)		 ::Dynamic _hx_tmp2 = ::haxe::Log_obj::trace;
HXDLIN(  25)		::String _hx_tmp3 = (HX_("LuaJIT version: ",fb,95,09,43) + linc::lua::versionJIT());
HXDLIN(  25)		_hx_tmp2(_hx_tmp3,::hx::SourceInfo(HX_("test/Test.hx",8f,7f,93,a4),25,HX_("Test",72,f4,d2,37),HX_("main",39,38,56,48)));
HXLINE(  27)		luaL_dofile(vm,HX_("script.lua",d5,d9,c1,2c));
HXLINE(  40)		 ::haxe::ds::StringMap _g =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXDLIN(  40)		_g->set(HX_("v",76,00,00,00),HX_("five",32,d7,bb,43));
HXLINE(  35)		::cpp::VirtualArray testValues = ::cpp::VirtualArray_obj::__new(6)->init(0,::cpp::VirtualArray_obj::__new(2)->init(0,HX_("Int",cf,c4,37,00))->init(1,1))->init(1,::cpp::VirtualArray_obj::__new(2)->init(0,HX_("Float",7c,35,c4,95))->init(1,((Float)2.0)))->init(2,::cpp::VirtualArray_obj::__new(2)->init(0,HX_("String",f1,9c,c4,45))->init(1,HX_("three",5e,54,90,0f)))->init(3,::cpp::VirtualArray_obj::__new(3)->init(0,HX_("Array[1]",4e,4c,2b,c9))->init(1,::cpp::VirtualArray_obj::__new(1)->init(0,HX_("four",e6,63,c0,43)))->init(2,1))->init(4,::cpp::VirtualArray_obj::__new(3)->init(0,HX_("Map.v",04,82,4d,96))->init(1,_g)->init(2,HX_("v",76,00,00,00)))->init(5,::cpp::VirtualArray_obj::__new(3)->init(0,HX_("Anon.v",f4,92,f8,9c))->init(1, ::Dynamic(::hx::Anon_obj::Create(1)
            			->setFixed(0,HX_("v",76,00,00,00),HX_("six",22,9f,57,00))))->init(2,HX_("v",76,00,00,00)));
HXLINE(  43)		::haxe::Log_obj::trace(HX_("from haxe:",1e,8a,40,fc),::hx::SourceInfo(HX_("test/Test.hx",8f,7f,93,a4),43,HX_("Test",72,f4,d2,37),HX_("main",39,38,56,48)));
HXLINE(  44)		 ::Dynamic _hx_tmp4 = ::haxe::Log_obj::trace;
HXDLIN(  44)		 ::Dynamic _hx_tmp5 = ::llua::Convert_obj::callLuaFunction(vm,HX_("fromHaxe",b0,02,d4,a2),::cpp::VirtualArray_obj::__new(1)->init(0,testValues),null());
HXDLIN(  44)		_hx_tmp4(_hx_tmp5,::hx::SourceInfo(HX_("test/Test.hx",8f,7f,93,a4),44,HX_("Test",72,f4,d2,37),HX_("main",39,38,56,48)));
HXLINE(  45)		::haxe::Log_obj::trace(HX_("to haxe:",ef,2c,3b,e0),::hx::SourceInfo(HX_("test/Test.hx",8f,7f,93,a4),45,HX_("Test",72,f4,d2,37),HX_("main",39,38,56,48)));
HXLINE(  46)		 ::Dynamic _hx_tmp6 = ::haxe::Log_obj::trace;
HXDLIN(  46)		 ::Dynamic _hx_tmp7 = ::llua::Convert_obj::callLuaFunction(vm,HX_("toHaxe",41,9f,c1,7a),null(),true);
HXDLIN(  46)		_hx_tmp6(_hx_tmp7,::hx::SourceInfo(HX_("test/Test.hx",8f,7f,93,a4),46,HX_("Test",72,f4,d2,37),HX_("main",39,38,56,48)));
HXLINE(  49)		{
HXLINE(  49)			::llua::Convert_obj::toLua(vm,( ( ::Dynamic)(::hx::ClassOf< ::Testing >()) ));
HXDLIN(  49)			lua_setglobal(vm,HX_("haxeValue",6b,f1,30,03));
            		}
HXLINE(  50)		::llua::Convert_obj::callLuaFuncNoReturns(vm,HX_("test",52,c8,f9,4c),null());
HXLINE(  59)		lua_close(vm);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(Test_obj,main,(void))


Test_obj::Test_obj()
{
}

bool Test_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"main") ) { outValue = main_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *Test_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *Test_obj_sStaticStorageInfo = 0;
#endif

::hx::Class Test_obj::__mClass;

static ::String Test_obj_sStaticFields[] = {
	HX_("main",39,38,56,48),
	::String(null())
};

void Test_obj::__register()
{
	Test_obj _hx_dummy;
	Test_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("Test",72,f4,d2,37);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Test_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Test_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< Test_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Test_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Test_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

