// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_Testing
#include <Testing.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_095d71599b3ec0e1_7_new,"Testing","new",0x4a3b24a2,"Testing.new","Test.hx",7,0x8afb218c)
HX_LOCAL_STACK_FRAME(_hx_pos_095d71599b3ec0e1_9_die,"Testing","die",0x4a339182,"Testing.die","Test.hx",9,0x8afb218c)
HX_LOCAL_STACK_FRAME(_hx_pos_095d71599b3ec0e1_12_test,"Testing","test",0xad7c2dd0,"Testing.test","Test.hx",12,0x8afb218c)

void Testing_obj::__construct(){
            	HX_STACKFRAME(&_hx_pos_095d71599b3ec0e1_7_new)
HXDLIN(   7)		this->x = 1;
            	}

Dynamic Testing_obj::__CreateEmpty() { return new Testing_obj; }

void *Testing_obj::_hx_vtable = 0;

Dynamic Testing_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Testing_obj > _hx_result = new Testing_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Testing_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x4b4790f0;
}

void Testing_obj::die(){
            	HX_STACKFRAME(&_hx_pos_095d71599b3ec0e1_9_die)
HXDLIN(   9)		::haxe::Log_obj::trace(HX_("no way i died",8b,f6,d5,cc),::hx::SourceInfo(HX_("test/Test.hx",8f,7f,93,a4),9,HX_("Testing",b0,eb,27,8b),HX_("die",40,3d,4c,00)));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Testing_obj,die,(void))

void Testing_obj::test(){
            	HX_STACKFRAME(&_hx_pos_095d71599b3ec0e1_12_test)
HXDLIN(  12)		::haxe::Log_obj::trace(HX_("YAAAAAAYYYYYYYY",39,44,a9,22),::hx::SourceInfo(HX_("test/Test.hx",8f,7f,93,a4),12,HX_("Testing",b0,eb,27,8b),HX_("test",52,c8,f9,4c)));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Testing_obj,test,(void))


::hx::ObjectPtr< Testing_obj > Testing_obj::__new() {
	::hx::ObjectPtr< Testing_obj > __this = new Testing_obj();
	__this->__construct();
	return __this;
}

::hx::ObjectPtr< Testing_obj > Testing_obj::__alloc(::hx::Ctx *_hx_ctx) {
	Testing_obj *__this = (Testing_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Testing_obj), false, "Testing"));
	*(void **)__this = Testing_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

Testing_obj::Testing_obj()
{
}

::hx::Val Testing_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"x") ) { return ::hx::Val( x ); }
		break;
	case 3:
		if (HX_FIELD_EQ(inName,"die") ) { return ::hx::Val( die_dyn() ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"test") ) { return ::hx::Val( test_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val Testing_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"x") ) { x=inValue.Cast< int >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Testing_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("x",78,00,00,00));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Testing_obj_sMemberStorageInfo[] = {
	{::hx::fsInt,(int)offsetof(Testing_obj,x),HX_("x",78,00,00,00)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *Testing_obj_sStaticStorageInfo = 0;
#endif

static ::String Testing_obj_sMemberFields[] = {
	HX_("x",78,00,00,00),
	HX_("die",40,3d,4c,00),
	HX_("test",52,c8,f9,4c),
	::String(null()) };

::hx::Class Testing_obj::__mClass;

void Testing_obj::__register()
{
	Testing_obj _hx_dummy;
	Testing_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("Testing",b0,eb,27,8b);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Testing_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Testing_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Testing_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Testing_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

