// Generated by Haxe 4.3.7
#ifndef INCLUDED_Testing
#define INCLUDED_Testing

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(Testing)



class HXCPP_CLASS_ATTRIBUTES Testing_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Testing_obj OBJ_;
		Testing_obj();

	public:
		enum { _hx_ClassId = 0x4b4790f0 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="Testing")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"Testing"); }
		static ::hx::ObjectPtr< Testing_obj > __new();
		static ::hx::ObjectPtr< Testing_obj > __alloc(::hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Testing_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Testing",b0,eb,27,8b); }

		int x;
		void die();
		::Dynamic die_dyn();

		void test();
		::Dynamic test_dyn();

};


#endif /* INCLUDED_Testing */ 
